<?php
$this->headTitle('Paiement');

$form->get('username')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Votre nom',
    'required' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('card')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'4978...',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('cvv')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'123',
    'required' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('expiration')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'MM/AA',
    'required' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<h1 id='maintitle'>Informations de paiement</h1><hr class='bottomSpace line'>

<form class="form-signin" method="post">

    <?php if ($isError): ?>
    <div class="alert alert-warning" role="alert">
        Le paiement n'a pas abouti. Veuillez réessayer.
    </div>
    <?php endif; ?>
    <?= $this->formLabel($form->get('username')); ?>
    <?= $this->formElement($form->get('username')); ?>
    <?= $this->formLabel($form->get('card')); ?>
    <?= $this->formElement($form->get('card')); ?>
    <?= $this->formLabel($form->get('cvv')); ?>
    <?= $this->formElement($form->get('cvv')); ?>
    <?= $this->formLabel($form->get('expiration')); ?>
    <?= $this->formElement($form->get('expiration')); ?>
    <?= $this->formElement($form->get('csrf')) ?>
    <button class="btn1" type="submit">Payer <?= $prixTotal ?> €</button>

</form>