<?php
$this->headTitle('Mon Compte');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Votre email',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

    $form->get('password')->setAttributes([
        'class'=>'form-control', 
        'placeholder'=>'Votre mot de passe',
        'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
?>

<h1 id='maintitle'>Mon Compte : <?= $user['username'] ?></h1><hr class='bottomSpace line'>

<?php if($modif): ?>

    <p>Votre email a bien été modifié !</p>

<?php endif ?>

<form class="form-signin" method="post">
    <?= $this->formLabel($form->get('email')); ?>
    <?= $this->formElement($form->get('email')); ?>
    <?= $this->formLabel($form->get('password')); ?>
    <?= $this->formElement($form->get('password')); ?>
    <?= $this->formElement($form->get('csrf')) ?>
    <button class="btn1">Valider les changements</button>
</form>