<?php
$this->headTitle('Modification');

$form->get('nom')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Nom du produit'
    ]);

$form->get('prix')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Prix du produit'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Description'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<?php if($error): ?>

<p>L'un des champs n'est pas correct !</p>

<?php endif ?>

<h1>Ajout d'un produit</h1>

<img class= 'imgItem' src="<?= $image ?>">

<form class="form-edit" method="post">

    <?= $this->formLabel($form->get('nom')); ?>
    <?= $this->formElement($form->get('nom')); ?>
    <?= $this->formLabel($form->get('prix')); ?>
    <?= $this->formElement($form->get('prix')); ?>
    <?= $this->formLabel($form->get('description')); ?>
    <?= $this->formElement($form->get('description')); ?>
    <?= $this->formElement($form->get('image')); ?>
    <button class="btn btn-primary btn1" type="submit">Valider le nouveau produit</button>

</form>