<h1 id='maintitle'>Mes fiches</h1><hr class='bottomSpace line'>

<!-- <?php if(!empty($nameProductDeleted)): ?>
    <p>Le produit <?= $nameProductDeleted ?> a bien été supprimé.</p>
    <?php endif ?> -->

<a href="/add"><button type="button" class='btn btn-primary btn1'>Ajouter une fiche</button></a>

<?php if(!empty($fiches)): ?>
<?php foreach ($fiches as $f) : ?>
<a href="/editfiche/<?= $f->_id ?>"><div class='row item'>

    <div class='col-sm-2'>
        <h2 class='secontitle'><?= $f->_nom ?></h2>
    </div>

    <div class='col-sm-10 itemTxt'>
        <p class='desc'> <?= $f->_description ?> </p><br/>
    </div>
    <a href="/delete/<?= $f->_id ?>?page=<?= $page ?>"><button type="button" class='btn btn-primary btn1'>Supprimer</button></a>
</div></a>
<?php endforeach; ?>
<?php else: ?>
    <h2>Vous n'avez créé aucune fiche pour l'instant !</h2>
<?php endif ?>