<?php
$this->headTitle('Modification');

$form->get('nom')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Nom de la fiche'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Description'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<?php if($error): ?>

<p>L'un des champs n'est pas correct !</p>

<?php endif ?>

<?php if($modif): ?>

<p>Modification effectué !</p>

<?php endif ?>

<?php if($ajout): ?>

<p>La fiche a été crée !</p>

<?php endif ?>

<h1>Modification de la fiche : <?= $fiche->_nom ?></h1>

<form class="form-edit" method="post">

    <?= $this->formLabel($form->get('nom')); ?>
    <?= $this->formElement($form->get('nom')); ?>
    <?= $this->formLabel($form->get('description')); ?>
    <?= $this->formElement($form->get('description')); ?>
    <button class="btn btn-primary btn1" type="submit">Valider les modifications</button>

</form>