<h1 id='maintitle'>Mes favoris</h1><hr class='bottomSpace line'>

<?php foreach ($fiches as $f) : ?>
<a href="/fiche/<?= $f->_id ?>"><div class='row item'>

    <div class='col-sm-2'>
        <h2 class='secontitle'><?= $f->_nom ?></h2>
        <p class='desc'>Par <?= $f->_userName ?></p>
    </div>

    <div class='col-sm-10 itemTxt'>
        <p class='desc'> <?= $f->_description ?> </p><br/>
    </div>
</div></a>
<?php endforeach; ?>