<h1 id='maintitle'>Votre historique d'achat : </h1><hr class='bottomSpace line'>

<?php if(!empty($products)): ?>
<div class='row'>

    <div class='col-lg-6'>
        <?php foreach ($products as $p) : ?>
            <div class='panierItem'>
                <img class= 'smImg' src="<?= $p->_image ?>">
                <span class='panierTitre'><?= $p->_nom ?></span>
                <span class='panierPrice'><?= $p->_prix ?> €</span>

                <div class='blockButtonPanierBtn'>
                    <a href="/produit/<?= $p->_id ?>"><button class="btn1" type="button">Détail</button></a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php else: ?>
    <h2>Vous n'avez encore rien acheté sur notre site !</h2>
<?php endif ?>