<h1 id='maintitle'>Derniers articles</h1><hr class='bottomSpace line'>

<?php if(!empty($productPanier)): ?>
    <p>Le produit <?= $productPanier->_nom ?> a été ajouté au panier !</p>
<?php endif ?>

<?php foreach ($products as $p) : ?>
<div class='row item'>

    <div class='col-sm-2'>
        <img class= 'imgItem' src="<?= $p->_image ?>">
    </div>

    <div class='col-sm-10 itemTxt'>
        <h2 class='secontitle'> <?= $p->_nom ?> </h2>
        <span class='desc'> <?= $p->_description ?> </span><br/>
        <span class='price'>
            <?= $p->_prix ?> €
            <a href="/produit/<?= $p->_id ?>"><button type="button" class='btn btn-primary btn1'>Détail</button></a>
            <a href="/addpanier/<?= $p->_id ?>?redirectUrl=/?idProductAddToPanier=<?= $p->_id ?>"><button type="button" class='btn btn-primary btn1'><i class='fa fa-shopping-cart iconNav'></i>Ajouter au panier</button></a>
        </span>
    </div>
</div>
<?php endforeach; ?>

<div class='btn-group pageGroup'>

    <?php if($page != $pagePrecedente): ?>
    <a href="/page/<?= $pagePrecedente ?>"><button *ngIf="numPage!=1" type="button" class='btn btn-primary' id="pagePrecedente">Page précédente</button></a>
    <?php endif ?>
    <button type="button" class='btn btn-primary'><?= $page ?></button>
    <a href="/page/<?= $pageSuivante ?>"><button *ngIf="numPage!=pageMax" type="button" class='btn btn-primary' id="pageSuivante">Page suivante</button></a>
</div>