<h1 id='maintitle'>Les plus populaires</h1><hr class='bottomSpace line'>
<?php foreach ($favoris as $f) : ?>
<div class='row item'>

    <div class='col-sm-2'>
    <a href="/fiche/<?= $f->_id ?>">
        <h2 class='secontitle'><?= $f->_nom ?></h2>
        <p class='desc'>Par <?= $f->_userName ?></p>
    </a>
    </div>

    <div class='col-sm-10 itemTxt'>
        <p class='desc'> <?= $f->_description ?> </p><br/>
    </div>
</div>

<hr class='bottomSpace line'>

<?php endforeach; ?>

<hr class='bottomSpace line'>

<h1 id='maintitle'>Galerie</h1><hr class='bottomSpace line'>

<form method="post">
    Recherche par titre : <input type="text" name="recherche"> <input type="submit" value="Rechercher">
</form>

<hr class='bottomSpace line'>

<?php foreach ($fiches as $f) : ?>
<div class='row item'>

    <div class='col-sm-2'>
    <a href="/fiche/<?= $f->_id ?>">
        <h2 class='secontitle'><?= $f->_nom ?></h2>
        <p class='desc'>Par <?= $f->_userName ?></p>
    </a>
    </div>

    <div class='col-sm-10 itemTxt'>
        <p class='desc'> <?= $f->_description ?> </p><br/>
    </div>
</div>

<hr class='bottomSpace line'>

<?php endforeach; ?>

<hr class='bottomSpace line'>

<div class='btn-group pageGroup'>

    <?php if($page != $pagePrecedente): ?>
    <a href="/page/<?= $pagePrecedente ?>"><button *ngIf="numPage!=1" type="button" class='btn1' id="pagePrecedente">Page précédente</button></a>
    <?php endif ?>
    <button type="button" class='btn1'><?= $page ?></button>
    <a href="/page/<?= $pageSuivante ?>"><button *ngIf="numPage!=pageMax" type="button" class='btn1' id="pageSuivante">Page suivante</button></a>
</div>