<h1 id='maintitle'>Galerie</h1><hr class='bottomSpace line'>

<?php foreach ($fiches as $f) : ?>
<div class='row item'>

    <div class='col-sm-10 itemTxt'>
        <h2 class='secontitle'> <?= $f->_nom ?> </h2>
        <p class='desc'> <?= $f->_description ?> </p><br/>
    </div>
</div>
<?php endforeach; ?>

<div class='btn-group pageGroup'>

    <?php if($page != $pagePrecedente): ?>
    <a href="/page/<?= $pagePrecedente ?>"><button *ngIf="numPage!=1" type="button" class='btn1' id="pagePrecedente">Page précédente</button></a>
    <?php endif ?>
    <button type="button" class='btn1'><?= $page ?></button>
    <a href="/page/<?= $pageSuivante ?>"><button *ngIf="numPage!=pageMax" type="button" class='btn1' id="pageSuivante">Page suivante</button></a>
</div>