<h1 id='maintitle'>Détail article : <?= $product->_nom ?></h1><hr class='bottomSpace line'>

<?php if(!empty($productPanier)): ?>
    <p>Le produit <?= $productPanier->_nom ?> a été ajouté au panier !</p>
<?php endif ?>

<img src="<?= $product->_image ?>" alt="image de l'article">
<h2 class='secontitle titleUp'>Description</h2>
<p><?= $product->_description ?></p>
<span class='priceItem'>
    <?= $product->_prix ?> € Seulement !<br/>
    <a href="/addpanier/<?= $product->_id ?>?redirectUrl=/produit/<?= $product->_id ?>?idProductAddToPanier=<?= $product->_id ?>"><button class='btn1' type="button" id="addPanier">
        <i class='fa fa-shopping-cart iconNav'></i>Ajouter au panier
    </button></a>
</span>
